modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[32,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="Apache-2.0"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

# The modid of the mod
modId = "" #mandatory

# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="${file.jarVersion}" #mandatory

# A display name for the mod
displayName = "" #mandatory

# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://discord.gg/UYGSn94" #optional

# A file name (in the root of the mod JAR) containing a logo for display
#logoFile = "logo.png" #optional

# A text field displayed in the mod UI
credits = "" #optional

# A text field displayed in the mod UI
authors = "HellionGames" #optional

# The description text for the mod (multi line!) (#mandatory)
description = '''

'''

[[dependencies.modid]]
modId="forge"
mandatory=true
versionRange="[32,)"
ordering="NONE"
side="BOTH"
[[dependencies.modid]]
modId="minecraft"
mandatory = true
versionRange = "[1.16.3,1.17)"
ordering = "NONE"
side="BOTH"