name: Bump Forge

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * 0' # At 12am on Sunday

jobs:
  bump:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Get declared Minecraft version
        id: properties_minecraft_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: ./build.properties
          property: MINECRAFT_VERSION

      - name: Get latest Forge version
        id: latest_forge_version
        run: |
          curl -s 'https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json' | \
          jq --raw-output '"::set-output name=value::"+.promos["${{ steps.latest_minecraft_version.outputs.value }}-latest"]'
        
      - name: Get declared Forge version
        id: properties_forge_version
        uses: christian-draeger/read-properties@1.0.1
        with:
          path: ./build.properties
          property: FORGE_VERSION

      - name: Update Forge version
        if: ${{ steps.latest_forge_version.outputs.value != steps.properties_forge_version.outputs.value }}
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: ./build.properties
          property: FORGE_VERSION
          value: ${{ steps.latest_forge_version.outputs.value }}
      
      - name: Commit changes
        if: ${{ steps.latest_forge_version.outputs.value != steps.properties_forge_version.outputs.value }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add build.properties
          git commit --verbose -m "chore: Updated Forge version
          This is an automated commit, it was made by a GitHub workflow.
          Action: https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          "
      - name: Push changes
        if: ${{ steps.latest_forge_version.outputs.value != steps.properties_forge_version.outputs.value }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

